---
title: "Correção de sementesCazumba e producaoCazumba"
output: html_notebook
---

```{r dataReading, include=FALSE}
producaoCazumba = read.csv(here("data", "producao.csv"), sep = ";")
sementesCazumba = read.csv(here("data", "sementes.csv"), sep = ";")
```

Adicionar todos os anos
```{r}
sementesCazumba[nrow(sementesCazumba)+1,] <- c("Coletivo",
                                               NA,NA,NA,NA,"Cazumba",2021)
sementesCazumba[nrow(sementesCazumba)+1,] <- c("Davi",
                                               NA,NA,NA,NA,"Cazumba",2021)
sementesCazumba[nrow(sementesCazumba)+1,] <- c("Dimar",
                                               NA,NA,NA,NA,"Cazumba",2018)
sementesCazumba[nrow(sementesCazumba)+1,] <- c("Dimar",
                                               NA,NA,NA,NA,"Cazumba",2021)
sementesCazumba[nrow(sementesCazumba)+1,] <- c("Irmãos Gamas",
                                               NA,NA,NA,NA,"Cazumba",2018)
sementesCazumba[nrow(sementesCazumba)+1,] <- c("Irmãos Gamas",
                                               NA,NA,NA,NA,"Cazumba",2021)
sementesCazumba[nrow(sementesCazumba)+1,] <- c("Mariazinha",
                                               NA,NA,NA,NA,"Cazumba",2021)
sementesCazumba[nrow(sementesCazumba)+1,] <- c("Marizan",
                                               NA,NA,NA,NA,"Cazumba",2018)
sementesCazumba[nrow(sementesCazumba)+1,] <- c("Marizan",
                                               NA,NA,NA,NA,"Cazumba",2021)
sementesCazumba[nrow(sementesCazumba)+1,] <- c("Zequinha",
                                               NA,NA,NA,NA,"Cazumba",2018)
sementesCazumba[nrow(sementesCazumba)+1,] <- c("Zequinha",
                                               NA,NA,NA,NA,"Cazumba",2021)
sementesCazumba[nrow(sementesCazumba)+1,] <- c("Zirmão",
                                               NA,NA,NA,NA,"Cazumba",2021)
sementesCazumba[nrow(sementesCazumba)+1,] <- c("Zirmão 2",
                                               NA,NA,NA,NA,"Cazumba",2018)
sementesCazumba[nrow(sementesCazumba)+1,] <- c("Zirmão 2",
                                               NA,NA,NA,NA,"Cazumba",2021)

sementesCazumba[,c(2:5,7)] <- suppressWarnings(as.integer(unlist(sementesCazumba[,c(2:5,7)])))

producaoCazumba[nrow(producaoCazumba)+1,] <- c("Dimar",
                                               NA,NA,NA,NA,"Cazumba",2018)
producaoCazumba[nrow(producaoCazumba)+1,] <- c("Irmãos Gamas",
                                               NA,NA,NA,NA,"Cazumba",2018)
producaoCazumba[nrow(producaoCazumba)+1,] <- c("Marizan",
                                               NA,NA,NA,NA,"Cazumba",2018)
producaoCazumba[nrow(producaoCazumba)+1,] <- c("Zequinha",
                                               NA,NA,NA,NA,"Cazumba",2018)
producaoCazumba[nrow(producaoCazumba)+1,] <- c("Zirmão 2",
                                               NA,NA,NA,NA,"Cazumba",2018)

producaoCazumba[,c(2:5,7)] <- suppressWarnings(as.integer(unlist(producaoCazumba[,c(2:5,7)])))
```

Arquivos de saída
```{r}
sementesCazumbaCompleta = as.data.frame(sementesCazumba)
producaoCazumbaCompleta = as.data.frame(producaoCazumba)
write.csv(sementesCazumbaCompleta, here("data", "sementesCazumbaCompleta.csv"))
write.csv(producaoCazumbaCompleta, here("data", "producaoCazumbaCompleta.csv"))
```