---
title: "Monitoramento Participativo da Biodiversidade"
author: "Fernando Lima, D.Sc."
output:
  word_document: default
  html_document:
    df_print: paged 
---

```{r packages, include=FALSE}
rm(list = ls(all = TRUE))
#install.packages("here")
install.packages("tidyverse")
#install.packages("ggplot2")
#install.packages("vctrs")
library(tidyverse)
library(xlsx)
library(ggplot2)
library(here)
library(vctrs)
library(dplyr)
library(readr)
```

# CASTANHA DA AMAZÔNIA - FORMULÁRIO 2A

-   Subprograma Terrestre

    -   Componente Florestal

        -   Alvo Complementar: Castanha da Amazônia

            -   Protocolo Básico

Os dados, scripts e informações aqui contidas estão disponíveis no GitHub no endereço: <https://github.com/pardalismitis/monitoraCastanha>

```{r dataReading, include=FALSE}
manejo = 
  read.csv(here("data", "formulario2bManejo.csv"),
           #sep = ";",
           na.strings = c("", "NA"),
           encoding = "UTF-8"
           )
id =
  read.csv(here("data", "Id.csv"),
           na.strings = c("","NA")
           )

unique(id$Nome_Castanhal)

manejo <- manejo %>%
  dplyr::full_join(., id, by = "ID")
```


```{r}
dados <- manejo
dados <- dados %>%
  relocate(UC)#%>% 
```

```{r}
dados <- dados %>%
  dplyr::mutate(
    UC = replace(UC, UC == "Cautario",
                 "Reserva Extrativista Rio do Cautário"
                 )
  ) %>%
  dplyr::mutate(
    UC = replace(UC, UC == "Cazumba",
                 "Reserva Extrativista do Cazumbá-Iracema"
                 )
  ) %>%
  dplyr::mutate(
    UC = replace(UC, UC == "Lago_Cuina",
                 "Reserva Extrativista Lago do Cuniã"
                 )
  ) %>%
  dplyr::mutate(
    UC = replace(UC, UC == "ROP",
                 "Reserva Extrativista do Rio Ouro Preto"
                 )
  )
```

```{r}
dadosTemp <- dados
dados <- dados %>%
  dplyr::mutate(
    Ano = substr(Cole_ini, nchar(Cole_ini)-4+1, nchar(Cole_ini))
  ) %>%
  relocate(Ano, .after = UC) %>%
  dplyr::mutate(
    Nome_Castanhal = case_when(
      Nome_Castanhal == "S’tio" ~ "Sitio",
      Nome_Castanhal == "2 irm‹os" ~ "2_irmaos",
      Nome_Castanhal == "Araœjo" ~ "Araujo",
      Nome_Castanhal == "Soc—" ~ "Soco",
      Nome_Castanhal == "Acapœ" ~ "Acapulco",
      Nome_Castanhal == "Ara\u008d‡" ~ "Araca",
      TRUE ~ Nome_Castanhal)
    ) %>%
  dplyr::relocate(
    Nome_Castanhal, .after = Ano
    ) %>%
  dplyr::mutate(
    Representante = replace(Representante, Representante == "Tito Gon\u008dalves Neves",
                 "Tito Goncalves Neves"
                 )
  ) %>%
  dplyr::relocate(
    Representante, .after = Nome_Castanhal
    ) %>%
  dplyr::mutate(
    Mes = substr(Cole_ini, nchar(Cole_ini)-7+1, nchar(Cole_ini)-5)
  ) %>%
  dplyr::relocate(
    Mes, .after = Representante
    ) %>%
  dplyr::mutate(
    Mes = case_when(
      Mes == "01" ~ "janeiro",
      Mes == "02" ~ "fevereiro",
      Mes == "03" ~ "marco",
      Mes == "11" ~ "novembro",
      Mes == "12" ~ "dezembro",
      TRUE ~ Mes)
    ) %>%
  dplyr::mutate(
    Cort_cipo = tolower(Cort_cipo)
  ) %>%
  dplyr::relocate(
    Cort_cipo, .after = Mes
  ) %>%
  dplyr::mutate(
    Limpeza_vege = tolower(Limpeza_vege)
  ) %>%
  dplyr::relocate(
    Limpeza_vege, .after = Cort_cipo

  ) %>%
  dplyr::mutate(
    Queima_vegetacao = tolower(Queima_vegetacao)
  ) %>%
  dplyr::relocate(
    Queima_vegetacao, .after = Limpeza_vege
  ) %>%
  dplyr::mutate(
    Mudas = tolower(Mudas)
  ) %>%
  dplyr::relocate(
    Mudas, .after = Queima_vegetacao
  ) %>%
  dplyr::relocate(
    Quant, .after = Mudas
  ) %>%
  dplyr::mutate(
    Plantou = tolower(Plantou)
  ) %>%
  dplyr::relocate(
    Plantou, .after = Quant
  ) %>%
  dplyr::relocate(
    Quant.1, .after = Plantou
  ) %>%
  dplyr::mutate(
    Sangrou = tolower(Sangrou)
  ) %>%
  dplyr::relocate(
    Sangrou, .after = Quant.1
  ) %>%
  dplyr::relocate(
    Como, .after = Sangrou
  ) %>%
  dplyr::mutate(
    Epoca = substr(S_ini, nchar(S_ini)-7+1, nchar(S_ini)-5)
  ) %>%
  dplyr::relocate(
    Epoca, .after = Como
  ) %>%
  dplyr::mutate(
    Epoca = case_when(
      Epoca == "01" ~ "janeiro",
      Epoca == "02" ~ "fevereiro",
      Epoca == "03" ~ "marco",
      Epoca == "11" ~ "novembro",
      Epoca == "12" ~ "dezembro",
      TRUE ~ Epoca)
    ) %>%
  dplyr::mutate(
    Cas_morreu = tolower(Cas_morreu)
  ) %>%
  dplyr::relocate(
    Cas_morreu, .after = Epoca
  ) %>%
  dplyr::relocate(
    Cas_morreu_q, .after = Cas_morreu
  ) %>%
  dplyr::relocate(
    Cas_morreu_c, .after = Cas_morreu_q
  ) %>%
  dplyr::mutate(
    Cas_morreu_c = replace(Cas_morreu_c, Cas_morreu_c == "Morreuemp\u008e",
                 "Morreu_em_pe"
                 )
  )  
```


Exportação de dados

```{r exportaForm2a}

write.csv(dados, here("output", "formulario2b.csv"))
```
